### ISSUE TITLE
readme issue with skopeo ?

### ISSUE THREAD

**Issue by zeddii** [opencontainers/image-tools#112]
I'm trying to use the image-tools to import and transform containers to execute under runc. The oci-unpack, oci-create-runtime-bundle and validate seem to be just what I need (I was about to run them myself).

But I'm unable to execute the steps in the Readme.md to prove to myself that something simple works.

No matter what tool I use, I get a variant of:

 ./oci-unpack --ref latest busybox-oci busybox-bundle
warning: layer sha256:4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c has an unknown media type: application/vnd.oci.image.layer.v1.tar+gzip
unpacking failed: layer validation failed: invalid descriptor MediaType "application/vnd.oci.image.layer.v1.tar+gzip"

I've been bisecting the image-tools, skopeo, etc to try and figure out what combination of commits are the right ones to use (I have to work from source, since this goes into a build system for others to use and generate images).

Is this the tools ? Or did the docker hub / registry change to start returning gzip layers that are triggering the issue ?

**Comment by runcom** [comment]
That issue is being fixed with https://github.com/opencontainers/image-tools/pull/111 I guess.

**Comment by zeddii** [comment]
Well crap. I didn't think to check pending pull requests. I'll give that a go.

**Comment by zeddii** [comment]
Indeed this does fix the problem after I just updated my clone.
