### ISSUE TITLE
include URL to the project

### ISSUE THREAD

**Issue by philips** [opencontainers/image-tools#13]
_From @vbatts on September 13, 2016 20:0_

Anyone that uses the cli tools ought to have see a URL to the project in the usage (`--help`), so that:
- they can learn more on the spec that the tool is referencing
- they can report issues

_Copied from original issue: opencontainers/image-spec#307_

**Comment by philips** [comment]
_From @runcom on September 13, 2016 20:16_

@vbatts do we want the URL to show up only when `oci-image-tool --help` (or w/o `--help`) or with every subcommand? it requires to duplicate that URL to every subcommand if we go to show it on every subcommand. Is this for 0.5.0?

**Comment by philips** [comment]
_From @vbatts on September 13, 2016 21:4_

I wasn't think that every subcommand need it... but maybe? I'm not convinced. Only that it need to be discoverable.

And this is just a nice-to-have, not related to v0.5.0

**Comment by Sn0rt** [comment]
@vbatts hi, I am interesting in this issues and can for someting for this, but are you desing the command line ?

**Comment by vbatts** [comment]
@Sn0rt you're welcome to open a pull-request for this and the review would happen there

**Comment by Sn0rt** [comment]
#88 a simple version

**Comment by vbatts** [comment]
#88 is merged
