### ISSUE TITLE
cmd/oci-image-tool: is having empty refs/ a valid image?

### ISSUE THREAD

**Issue by philips** [opencontainers/image-tools#15]
_From @runcom on September 9, 2016 8:40_

$SUBJECT and basically, is it valid to have stuff under `blobs/` not referenced? Can I still package it up and validation is ok given there are no refs/? Should we print a warning (which can be silenced)?

_Copied from original issue: opencontainers/image-spec#287_

**Comment by philips** [comment]
_From @wking on September 9, 2016 9:4_

On Fri, Sep 09, 2016 at 01:40:15AM -0700, Antonio Murdaca wrote:
> $SUBJECT

I think so.  At least I don't see any “and there MUST be at least one
ref” language.  And if you cared about running images from the layour
that would be “and there MUST be at least one unpackable ref”
language.  And then you have to match the oci-layout version with the
media types that were unpackable when it was current (or is validity
in the eye of the validator?)… This is a bowl that I do not want to
fathom ;).

Maybe folks are just using an image-layout to ship some missing blobs.

I don't see any incentive to image-authors to publish ref-less blobs
and then pretend they are runnable, so I don't see a need to get into
the business of restricting refs.

> … and basically, is it valid to have stuff under `blobs/` not
> referenced?

Yes [1].

> Should we print a warning?

Warnings for “there are no refs” and “dangling blob sha256-abc…” sound
useful to me.  Maybe put the first behind ‘--log-level warn’ and the
second behind ‘--log-level info’ based on how likely I think they are
to be a mistake and how many lines will get printed if they exist ;).

[1]: https://github.com/opencontainers/image-spec/blame/e6a431f1584468f112a52c01a02d326199b99021/image-layout.md#L46

**Comment by philips** [comment]
_From @vbatts on September 13, 2016 19:20_

Both seem valid to me

**Comment by philips** [comment]
_From @runcom on September 13, 2016 19:25_

Alright, can we keep this open so we won't forget about adding some sort of warning/log when this happens

**Comment by xiekeyang** [comment]
I think it could be closed by https://github.com/opencontainers/image-spec/pull/533
