### ISSUE TITLE
org.opencontainers.ref.name should be org.opencontainers.image.ref.name

### ISSUE THREAD

**Issue by mcpat** [opencontainers/image-tools#167]
According to the [specification](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys) references for targets should be named as "org.opencontainers.image.ref.name".
In the code "org.opencontainers.ref.name" is used instead which currently leads to validation errors.

**Comment by q384566678** [comment]
The problem is dealt with in #152 , waiting for rebase.

**Comment by mcpat** [comment]
A sorry. I did not check the closed issues list!
