### ISSUE TITLE
Use github.com/sirupsen/logrus instead of github.com/Sirupsen/logrus

### ISSUE THREAD

**Issue by mgoltzsche** [opencontainers/image-tools#175]
Since image-tools refers to the logrus package with a capital letter it cannot be imported together with another package that uses the lower-case logrus package name since go build returns a case-insensitive import collision.

Thus unfortunately for instance I cannot import image-tools together with github.com/containers/image.

To solve this issue the glide dependency and corresponding imports should be updated to use the lower-case logrus package name since it has changed recently. According to https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276 the name change will not be reverted and most projects are already using the lower-case variant.

logrus references must be updated in the following files:
* glide.yaml
* image/manifest.go
* image/manifest_test.go
* cmd/oci-image-tool/main.go

**Comment by stevegt** [comment]
Without a new release tagged (#204), `go mod tidy` defaults to the old, most-recent tag, rather than the most recent commit, so by default #175 is not included.  Anyone running into this needs to explicitly include a more recent commit hash in their imports and/or go.mod file entry.
