### ISSUE TITLE
oci-image-tool: support multiple --ref in unpack and create-runtime-bundle

### ISSUE THREAD

**Issue by philips** [opencontainers/image-tools#19]
_From @runcom on September 6, 2016 17:14_

As the title says (validate has been fixed here https://github.com/opencontainers/image-spec/pull/265)

_Copied from original issue: opencontainers/image-spec#266_

**Comment by philips** [comment]
_From @runcom on September 6, 2016 17:19_

/cc @s-urbaniak PTAL at the linked PR also

**Comment by q384566678** [comment]
Since https://github.com/opencontainers/image-spec/pull/265 has benn merged, closing this issues.
