### ISSUE TITLE
oci-image-tool: Cleanup partially-unpacked directories on failures

### ISSUE THREAD

**Issue by philips** [opencontainers/image-tools#21]
_From @wking on September 1, 2016 18:16_

We might want a switch to turn this off, but I think the default should be to remove the unpack directory if we fail partway through the unpack.

Spun off from [here](https://github.com/opencontainers/image-spec/pull/240#issuecomment-244138589).

_Copied from original issue: opencontainers/image-spec#242_

**Comment by wking** [comment]
On Tue, Sep 20, 2016 at 07:48:16PM -0700, Brandon Philips wrote:
> We might want a switch to turn this off, but I think the default
> should be to remove the unpack directory if we fail partway through
> the unpack.

PR is #7; we can close this issue.

**Comment by wking** [comment]
> PR is #7; we can close this issue.

And #7 was [merged back in October][1], so we can definitely close this issue ;).

Also related is the larger bundle cleanup (vs. just the unpacked rootfs cleanup) floated in #172.  But that's distinct from this issue, so I see no reason to leave this issue open.

[1]: https://github.com/opencontainers/image-tools/pull/7#event-814956833

**Comment by q384566678** [comment]
As @wking said, closing this issus.
