### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by simar7** [opencontainers/image-tools#223]
I couldn't do a `go get -d github.com/opencontainers/image-tools/cmd/oci-image-tool` to download the project because of dependency issue. Is the project still maintained?

If it's not actively maintained, are there projects we should be looking at?

**Comment by cyphar** [comment]
I wouldn't say this project is unmaintained, but I would suggest that you look at https://github.com/openSUSE/umoci (full disclosure, this is a project I developed). There is currently an [open proposal to move `umoci` into OCI and to effectively replace this project as its spiritual successor](https://github.com/opencontainers/tob/pull/67).

**Comment by cyphar** [comment]
[umoci] is now an OCI project as a reference implementation of the OCI image-spec. I would strongly suggest people move to using umoci.

[umoci]: https://github.com/opencontainers/umoci

**Comment by simar7** [comment]
Awesome! Thank you for the update. I'll close this issue as my question is now resolved.
