### ISSUE TITLE
ReadMe should include description of how to install

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-tools#91]
The ReadMe should include a description (or link to a description) for how to install and run the OCI Image Tools.

**Comment by RobDolinMS** [comment]
Opening per discussion on OCI Dev ConCall.  /cc @vbatts

**Comment by Sn0rt** [comment]
Can I copy some examples from the existing markdown to ReadMe?

[oci-create-runtime-bundle](https://github.com/opencontainers/image-tools/tree/master/cmd/oci-create-runtime-bundle)
[oci-image-validate](https://github.com/opencontainers/image-tools/blob/master/cmd/oci-image-validate/oci-image-validate.1.md)
[oci-unpack](https://github.com/opencontainers/image-tools/blob/master/cmd/oci-unpack/oci-unpack.1.md)

**Comment by wking** [comment]
On Thu, Dec 01, 2016 at 01:34:08AM -0800, Sn0rt wrote:
> Can I copy some examples from the existing markdown to ReadMe?

I'd rather link to those man pages to stay DRY, although very brief
examples being copied over are ok (like runtime-tools did in
opencontainers/runtime-tools#47).  Another approach to this portion of
getting-started is an all-command man page (linked from the README)
like the one I floated in #5 [1].

#92 looks useful too.

[1]: https://github.com/opencontainers/image-tools/pull/5/files#diff-fc4edae5c4391cf1575e6630b1ba33b5R1

**Comment by JJ** [comment]
Definitely something should be done, either way

**Comment by wking** [comment]
On Wed, Dec 21, 2016 at 11:24:32AM -0800, Juan Julián Merelo Guervós wrote:
> Definitely something should be done, either way

I think #92 covers everything folks want from this issue.

**Comment by JJ** [comment]
It might, when it's closed. Thanks for pointing it out, anyway.

**Comment by wking** [comment]
Closable with #92 landed?
